language: cpp

os:
  - linux
  - osx

branches:
  only:
    - develop
    - master
    - testing

env:
  global:
    - secure: Wt43koA55PGba7TsJ85f9vHyW4b/QfPh2Ywhw5+40sba5Us4Y3h+l23VyVjQbXuHfCGgC+t5+AABm1ubhL4MjCvxzS9BepjhNN92LPXoLfBRM2AHhNLWMKLLxt4T7OofjnLPw21l6cjjVrlZZojVbN4MnuG2IPUeUzoEBuA5TPE=
    # KEY_PASSWORD
    - secure: "Mte2zY0rgIa4M4bIeSKijFAFOtFy+DahRYCUgOB60cuS4b/+HMHnfmVGMqnBKitC9KVzb5fctMt2pGPK2hdlirvfkOd9ctEaEd1qSzADJjfQUKqLReOfi1N6Ln2dYqlZoDjnYpGWwTUl/uX+KtWomYW2TCZZG/uJEeh3QYkxlJQ="
    # DEVELOPER_NAME
    - secure: "CrB159u8KEwtsiCxnwvnCumiRkGgL+9aFgI2dosUvj3PtfebcVdhzRKBt+17jLapLCQEYoml8RVszLNuYpZu8y/3DhCk4ftWMumnvKOp8CIFb/4BFKMZxyuw+HlMg5oKwY4GOopnHo4mTEM51pDHMP8rfIxCjLimVeDc0uZaaj8="
  matrix:
    - CONFIG=release
    #- CONFIG=debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && cd `brew --prefix`
      && echo "We are using QT 5.4.2, because we had troubles with the current 4ea4fd83963d1c1eb1e6fc024be9719f8010748f QT 5.5 brew. The deployed frameworks were loading libraries from /usr/local/Cellar/qt5 instead of the app bundle."
      && git checkout 00e46351980ad915424aad9316abffc19936809c Library/Formula/qt5.rb
      && cd -
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd ./tests
  - qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         ./../bin/tests/tests -platform minimal -txt
      && sudo pip install cpp-coveralls
      && coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*  > coveralls.log
      ;
    else
         ./../bin/tests/tests.app/Contents/MacOS/tests -platform minimal -txt
      ;
    fi
  - cd ./../src
  - echo "#define BUILD ""$TRAVIS_BUILD_NUMBER" > build_number.h
  - qmake QOwnNotes.pro CONFIG+=$CONFIG
  - make

before_deploy:
  # create debian package for linux and a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         VERSION_NUMBER=`cat version.h | sed "s/[^0-9,.]//g"`
      && cd ../travis
      && dpkg-deb -x QOwnNotes.deb build
      && mv ../src/QOwnNotes build/opt/QOwnNotes/
      && sed -i 's/VERSION_NUMBER/'"$VERSION_NUMBER"'/g' build/DEBIAN/control
      && dpkg -b build QOwnNotes.deb
      ;
    else
         ../travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         export GIT_TAG=linux-b$TRAVIS_BUILD_NUMBER
      ;
    else
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER
      ;
    fi
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/pbek/QOwnNotes --tags

deploy:
  - provider: releases
    api_key:
        secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
    file: QOwnNotes.deb
    skip_cleanup: true
    on:
        repo: pbek/QOwnNotes
        branch: master
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = linux
  - provider: releases
    api_key:
        secure: EyOMTm+fzo7rWhRMfROH8/jeJnSFmLFz4pfD/HuFJI2ohayHJOIfASMdg0d7N2cGFS9G7iuPUmQ1S56YC8BSnEefc3lASB1i5hiSOMWJV+lO3N1JBFCWxCBzHc9Hs+XKwHwyhZ5iIYncx+JHPYRNWtUD+A6SZHiZ+sVI48gYMyA=
    file: QOwnNotes.dmg
    skip_cleanup: true
    on:
        repo: pbek/QOwnNotes
        branch: master
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = osx

notifications:
  recipients:
    - developer@bekerle.com
  email:
    on_success: change
    on_failure: change
