os:
  - linux
  - osx

language: cpp

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install qt5-default qttools5-dev-tools

script:
  - cd src
  - qmake -project
  - qmake QOwnNotes.pro
  - make
