# lychee --base . './**/*.md' --exclude github\.com --exclude \.onion --exclude itunes\.apple\.com --exclude twitter\.com --exclude-path webpage/node_modules/ --exclude-path webpage/src/*/*/references\.md
exclude = [
  'github.com',
  '\.onion',
  'itunes\.apple\.com',
  'twitter\.com',
  'www.paypal.com/cgi-bin/webscr',
  'file:\/\/\/',
  'http:\/\/0\.0\.0\.0',
]
exclude_path = [
  'webpage/node_modules/',
  'webpage/src/faq/references.md',
  'webpage/src/ar',
  'webpage/src/de',
  'webpage/src/es',
  'webpage/src/fa',
  'webpage/src/fr',
  'webpage/src/hu',
  'webpage/src/it',
  'webpage/src/ko',
  'webpage/src/nl',
  'webpage/src/pl',
  'src/libraries',
  'webpage/src/changelog.md',
]
